server:
  port: 8000

zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      serviceId: users
      strip-prefix: false
    timers:
      path: /timers/**
      serviceId: gamelogic
      strip-prefix: false
    flowers:
      path: /flowers/**
      serviceId: gamelogic
      strip-prefix: false
    achievements:
      path: /achievements/**
      serviceId: gamification
      strip-prefix: false
  ignored-services: '*'

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

endpoints:
  routes:
    sensitive: false


#endpoints:
#  trace:
#    sensitive: false

#ribbon:
#  eureka:
#    enabled: false
